import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.css";
import { ShoppingCartProvider } from "./context/shop-context";
import RootLayout from "./rootlayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default RootLayout


